name: Hello
on: push
env:
  BRANCH: main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello, world"
      - run: echo "${BRANCH}"
      - uses: actions/checkout@v4
        env:
          BRANCH: main-override
        with:
          ref: ${{ env.BRANCH }}
